config/routes.rb
Rails.application.routes.draw do
  root to: "books#index"

  resources :books do
    resources :images do
      collection do
        post :check_existence
        post :upload
      end
      resources :texts, only: [:index, :new, :create, :show]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :images, dependent: :destroy

  with_options presence: true do
    validates :book_name
    validates :status
  end

  enum status: {
    not_started: 0,
    in_progress: 1,
    completed: 2
  }
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :book
  has_one :text, dependent: :destroy
  has_one_attached :image

  with_options presence: true do
    validates :page_number
    validates :image
  end
end

app/models/text.rb
class Text < ApplicationRecord
  belongs_to :book
  belongs_to :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def show
    @book = Book.eager_load(:images).find_by(id: params[:id])
    return render file: Rails.public_path.join('404.html').to_s, status: :not_found unless @book

    # 画像をページ番号の昇順で並べ替え、インスタンス変数に割り当てる
    @images = @book.images.order('page_number ASC')

    flash[:notice] = '登録が完了しました' if params[:notice].present?
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to root_path, notice: '登録が完了しました'
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def book_params
    params.require(:book).permit(:book_name, :status)
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def index
    @images = Image.includes(:book).all
  end

  def new
    @image = Image.new
    @book = Book.find_by(id: params[:book_id])
  end

  def check_existence
    book_id = params[:book_id]
    page_number = params[:page_number]
    book = Book.find_by(id: book_id)
    image_exists = book.images.exists?(page_number: page_number)
    render json: { exists: image_exists }
  end

  def create
    book_id = params[:book_id]
    @book = Book.find_by(id: book_id)

    uploaded_file = params[:image][:file]
    page_number = params[:image][:page_number]

    ActiveRecord::Base.transaction do
      # 既存の画像を確認
      existing_image = @book.images.find_by(page_number: page_number)
      if existing_image.present?
        unless ActiveModel::Type::Boolean.new.cast(params[:image][:overwrite])
          render json: { error: 'Image already exists' }, status: :conflict
          next
        end

        existing_image.image.purge # 既存の画像を削除
        existing_image.destroy # imageのカラムも削除

      end

      # 新しい画像を保存
      image = @book.images.build(page_number: page_number)
      image.image.attach(uploaded_file)
      if image.save
        render json: image, status: :created
      else
        render json: image.errors, status: :unprocessable_entity
      end
    end
  end

  private

  def image_params
    params.require(:image).permit(:page_number, images: []).merge(book_id: params[:book_id])
  end

  # ファイル名からページ番号を抽出
  def extract_page_number(filename)
    filename.split('.').first
  end
end

app/controllers/texts_controller.rb
class TextsController < ApplicationController
  def new
    @text = Text.new
    @image = Image.find(params[:image_id])
  end

  def create
    @image = Image.find(params[:image_id])

    # Active Storageから画像を取得して一時ファイルに保存
    download_blob_to_tempfile(@image.image.blob) do |tempfile|
      # RTesseractを使って一時ファイルからテキストを抽出
      image_rtesseract = RTesseract.new(tempfile.path, lang: 'jpn')
      extracted_text = image_rtesseract.to_s
      @text = Text.new(content: extracted_text, book_id: params[:book_id], image_id: params[:image_id])

      if @text.save
        redirect_to book_path(@text.book_id), notice: '文字変換が完了しました'
      else
        redirect_to book_path(@text.book_id), status: :unprocessable_entity
      end
    end
  end

  private

  def text_params
    params.require(:text).permit(:content, :fixed_content).merge(book_id: params[:book_id], image_id: params[:image_id])
  end

  # Active StorageのBlobを一時ファイルとしてダウンロード
  def download_blob_to_tempfile(blob)
    tempfile = Tempfile.new([blob.filename.to_s, blob.filename.extension_with_delimiter])
    tempfile.binmode
    tempfile.write(blob.download)
    tempfile.rewind
    yield(tempfile)
  ensure
    tempfile.close
    tempfile.unlink # 一時ファイルを削除
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/application/_errors.html.erb
<% if object.errors.present? %>
  <div id="error_explanation">
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/application/_flash_message.html.erb
<div class="container">
  <% flash.each do |flash_key, value| %>
    <% key = nil %>
    <% key = 'success' if flash_key == 'notice' %>
    <% key = 'danger' if flash_key == 'alert' %>
    <% if key %>
      <div class="alert alert-<%= key %>" role="alert">
        <div class="container">
          <%= value %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/application/_navbar.html.erb
<div class="menu">
  <div class="container">
    <div class="nav navbar navbar-expand-sm navbar-custom">
      <%= link_to 'OCRアプリ', root_path, class: 'navbar-brand' %>
      <div class="navbar-nav">

      </div>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<h1>本の一覧</h1>

<table class="table">
  <thead>
    <tr>
      <th scope="col">書籍名</th>
      <th scope="col">ステータス</th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= link_to book.book_name, book_path(book) %></td>
        <td><%= book.status %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to '本を新しく登録する', new_book_path, class: 'btn btn-primary mb-1' %>

app/views/books/new.html.erb
<%= form_with model: @book, local: true do |f| %>
  <%= render 'application/errors', object: @book %>

  <div class="form-group">
    <%= f.label :book_name %>
    <%= f.text_field :book_name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :status %>
    <%= f.select :status, Book.statuses.keys.map { |status| [status.humanize, status] }, {}, {class: "form-control"} %>
  </div>

  <div class="actions">
    <%= f.submit "登録", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/books/show.html.erb
<h1>本の詳細</h1>

<%= link_to '画像を新しく登録する', new_book_image_path(@book), class: 'btn btn-warning mb-1' %>

  <table class="table table-bordered">
    <thead>
      <tr>
        <th scope="col">ページ</th>
        <th scope="col">画像</th>
        <th scope="col">テキスト抽出</th>
      </tr>
    </thead>
    <tbody>
      <% @book.images.each do |image| %>
        <tr>
          <td class="col"><%= image.page_number %></td>
          <td class="col-5"><%= image_tag(image.image, class: "d-block mx-auto img-thumbnail", alt: "No Image") %></td>
          <td class="col-6">
            <% if image.text.present? %>
              <%= image.text.content %>
            <% else %>
              <%= form_tag(book_image_texts_path(@book, image), method: :post, id: 'ocr_form') do %>
                <%= submit_tag 'この画像からテキストを抽出', class: 'btn btn-primary' %>
              <% end %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/images/new.html.erb
<script>
  // Identifier 'bookId' has already been declared対策でvarを使用
  var bookId = "<%= @book.id %>";
</script>

<%= form_with model: @image, url: book_images_path(@book), html: { multipart: true, id: "file_form" } do |form| %>
  <%= form.hidden_field :book_id, value: @book.id %>
  <div id="dropzone" style="border: 2px dashed #ccc; padding: 20px; width: 300px; text-align: center;">
    ここにファイルをドラッグ＆ドロップ
  </div>
  <ul id="fileList"></ul>
  <%= form.file_field :images, multiple: true, direct_upload: true, style: "display: none;", id: "fileInput" %>
  <%= form.submit "アップロード" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OcrApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'application/navbar' %>
    <%= render 'application/flash_message' %>
    <%= yield %>
  </body>
</html>